# Generated by Django 1.11.23 on 2021-11-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0091_merge_20210717_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="influxdbstorage",
            name="enable_refresh_rp",
            field=models.BooleanField(default=True, verbose_name="是否周期刷新rp"),
        ),
    ]
