# Generated by Django 1.11.23 on 2021-09-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0089_auto_20210804_1612"),
        ("metadata", "0092_merge_20210803_1738"),
    ]

    operations = []
