# Generated by Django 1.11.23 on 2021-09-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0093_merge_20210914_1920"),
        ("metadata", "0093_merge_20210918_1114"),
        ("metadata", "0095_auto_20210926_2020"),
    ]

    operations = []
