# Generated by Django 1.11.23 on 2021-12-07 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0095_merge_20211207_1140"),
        ("metadata", "0095_merge_20211026_1640"),
    ]

    operations = []
