# Generated by Django 1.11.23 on 2021-11-12 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0102_timeseriesmetric_label"),
        ("metadata", "0102_merge_20211111_2316"),
    ]

    operations = []
