# Generated by Django 1.11.23 on 2021-12-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0107_merge_20211213_1707"),
        ("metadata", "0096_merge_20211217_1651"),
    ]

    operations = []
