# Generated by Django 1.11.23 on 2022-02-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0112_merge_20220217_2136"),
        ("metadata", "0099_auto_20220217_2207"),
    ]

    operations = []
