# Generated by Django 1.11.23 on 2022-05-23 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0119_merge_20220518_1607"),
        ("metadata", "0119_merge_20220517_1636"),
    ]

    operations = []
