# Generated by Django 1.11.23 on 2022-05-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0118_bcsclusterinfo_status'),
        ('metadata', '0119_merge_20220518_1607'),
    ]

    operations = [
    ]
