# Generated by Django 1.11.23 on 2022-06-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0120_merge_20220526_2033'),
        ('metadata', '0119_merge_20220608_2003'),
    ]

    operations = [
    ]
