# Generated by Django 1.11.23 on 2022-06-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0121_merge_20220609_1635"),
        ("metadata", "0120_merge_20220523_1042"),
    ]

    operations = []
