# Generated by Django 1.11.23 on 2022-09-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0130_merge_20220905_1516'),
        ('metadata', '0131_modify_datalink_stats_influxdb_storage_database'),
    ]

    operations = []
