# Generated by Django 1.11.23 on 2022-09-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0126_auto_20220815_1113'),
        ('metadata', '0132_merge_20220920_1441'),
    ]

    operations = []
