# Generated by Django 1.11.23 on 2022-09-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0126_auto_20220830_1649'),
        ('metadata', '0132_merge_20220906_1601'),
    ]

    operations = []
