# Generated by Django 1.11.23 on 2023-05-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0153_update_agent_id_host_id_biz_id'),
    ]

    operations = []
