# Generated by Django 1.11.23 on 2022-06-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_auto_20220524_2148'),
        ('calendars', '0005_auto_20220524_2024'),
    ]

    operations = [
    ]
