# Generated by Django 1.11.23 on 2021-12-07 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0075_merge_20211201_1646"),
        ("bkmonitor", "0075_merge_20211207_1142"),
    ]

    operations = []
