# Generated by Django 1.11.23 on 2021-12-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0076_merge_20211208_1123'),
        ('bkmonitor', '0076_merge_20211207_1145'),
    ]

    operations = [
    ]
