# Generated by Django 1.11.23 on 2021-12-31 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0077_merge_20211230_1522"),
        ("bkmonitor", "0076_intelligent_alarm_config_add_model_id"),
    ]

    operations = []
