# Generated by Django 1.11.23 on 2022-04-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0094_merge_20220425_1857"),
        ("bkmonitor", "0094_bcsnode_taints"),
    ]

    operations = []
