# Generated by Django 1.11.23 on 2022-06-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkmonitor", "0103_auto_20220601_1012"),
        ("bkmonitor", "0101_auto_20220524_2148"),
    ]

    operations = []
