# Generated by Django 1.11.23 on 2022-09-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0112_bk_monitorv3_202209131800'),
        ('bkmonitor', '0112_bcscluster_space_uid'),
    ]

    operations = []
