# Generated by Django 1.11.23 on 2022-09-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0112_auto_20220819_1806'),
        ('bkmonitor', '0112_bk_monitorv3_202209131800'),
    ]

    operations = []
