# Generated by Django 1.11.23 on 2022-09-28 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0115_merge_20220922_1919'),
        ('bkmonitor', '0116_merge_20220923_2022'),
    ]

    operations = []
