# Generated by Django 1.11.23 on 2022-10-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0118_merge_20221009_1508'),
        ('bkmonitor', '0118_merge_20220928_1800'),
    ]

    operations = []
