# Generated by Django 1.11.23 on 2023-03-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0128_merge_20230310_1041'),
        ('bkmonitor', '0129_merge_20230309_1320'),
    ]

    operations = []
